version: '3.8'

services:
  web:
    image: smaller-app-1:latest
    ports:
      - "5002:5002"
    depends_on:
      - mydb

  mydb:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: flaskdb             # Optional but recommended
      MYSQL_ROOT_HOST: '%' 

